language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit.xml